// NBS数据库
const nbsData = [
    {
        id: 1,
        name: "非机动车与人行的绿道",
        heatIsland: 4,
        flooding: 2,
        pollution: 2,
        recreation: 5,
        structure: 3,
        highDensity: 4,
        mediumDensity: 5,
        lowDensity: 3,
        innerLocation: 3,
        middleLocation: 5,
        outerLocation: 5,
        residential: 3,
        commercial: 3,
        road: 5,
        park: 5,
        agriculture: 2,
        waterfront: 3,
        difficulty: 3,
        function: "提供生态友好型交通方式，改善城市微气候",
        scenario: "道路系统、公园内部路径",
        image: "images/nbs-1.jpg"
    },
    {
        id: 2,
        name: "城市树木",
        heatIsland: 5,
        flooding: 2,
        pollution: 5,
        recreation: 3,
        structure: 3,
        highDensity: 5,
        mediumDensity: 5,
        lowDensity: 4,
        innerLocation: 5,
        middleLocation: 5,
        outerLocation: 5,
        residential: 5,
        commercial: 4,
        road: 5,
        park: 5,
        agriculture: 3,
        waterfront: 3,
        difficulty: 2,
        function: "改善空气质量，降低温度，增加遮荫",
        scenario: "街道、广场、居住区",
        image: "images/nbs-2.jpg"
    },
    // 添加剩余的NBS数据...
    {
        id: 7,
        name: "雨水花园",
        heatIsland: 3,
        flooding: 5,
        pollution: 3,
        recreation: 4,
        structure: 2,
        highDensity: 4,
        mediumDensity: 5,
        lowDensity: 5,
        innerLocation: 4,
        middleLocation: 5,
        outerLocation: 3,
        residential: 5,
        commercial: 4,
        road: 3,
        park: 5,
        agriculture: 3,
        waterfront: 4,
        difficulty: 3,
        function: "集雨、渗透、净化雨水，减轻内涝",
        scenario: "住宅区、公园、学校",
        image: "images/nbs-7.jpg"
    },
    {
        id: 20,
        name: "透水铺装",
        heatIsland: 3,
        flooding: 5,
        pollution: 2,
        recreation: 2,
        structure: 2,
        highDensity: 5,
        mediumDensity: 5,
        lowDensity: 5,
        innerLocation: 5,
        middleLocation: 5,
        outerLocation: 4,
        residential: 4,
        commercial: 5,
        road: 5,
        park: 4,
        agriculture: 3,
        waterfront: 3,
        difficulty: 2,
        function: "增加雨水渗透，减少径流，缓解热岛",
        scenario: "停车场、人行道、广场",
        image: "images/nbs-20.jpg"
    }
    // 添加所有NBS数据...
];
